'use client';

import { Inter } from 'next/font/google';
import { ThemeProvider } from 'styled-components';
import { Provider } from 'react-redux';

import { setupStore } from '../store';
import { Theme, GlobalStyles } from '../styles/themeConfig';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider store={setupStore()}>
          <ThemeProvider theme={Theme}>
            <GlobalStyles />
            {children}
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
